/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.juegotrivia;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.microsoft.sqlserver.jdbc.SQLServerConnection;
import com.mycompany.conexionSQLServer.Conexion;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class AgregarVerbos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVerbos
     */
    public AgregarVerbos() {
        initComponents();
        initStyles();
    }

    private void initStyles() {
        titulo.putClientProperty( "FlatLaf.styleClass", "h1" );
        verbo.putClientProperty( "FlatLaf.styleClass", "h1" );
        definicion.putClientProperty( "FlatLaf.styleClass", "h2" );
        agregarverbos.putClientProperty( "FlatLaf.styleClass", "h2" );
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    //String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    //String url = "jbdc.sqlserver://localhost:1433;databaseName=englishOdyssey;usar=sa;password=LolasO5566_;";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_AgregarVerbos = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        verbo = new javax.swing.JLabel();
        definicion = new javax.swing.JLabel();
        txtnombre_verbo = new javax.swing.JTextField();
        txtdefinicion = new javax.swing.JTextField();
        agregarverbos = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background_AgregarVerbos.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Agrega un verbo");

        verbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        verbo.setText("Verbo");

        definicion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        definicion.setText("Definicion");

        agregarverbos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agregarverbos.setText("Agregar verbos");
        agregarverbos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarverbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarverbosActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background_AgregarVerbosLayout = new javax.swing.GroupLayout(background_AgregarVerbos);
        background_AgregarVerbos.setLayout(background_AgregarVerbosLayout);
        background_AgregarVerbosLayout.setHorizontalGroup(
            background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_AgregarVerbosLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_AgregarVerbosLayout.createSequentialGroup()
                        .addComponent(regresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_AgregarVerbosLayout.createSequentialGroup()
                        .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(definicion)
                            .addComponent(verbo))
                        .addGap(125, 125, 125)
                        .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarverbos)
                            .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdefinicion, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtnombre_verbo)))
                        .addGap(341, 341, 341))))
        );
        background_AgregarVerbosLayout.setVerticalGroup(
            background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_AgregarVerbosLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(titulo)
                .addGap(97, 97, 97)
                .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre_verbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verbo))
                .addGap(33, 33, 33)
                .addGroup(background_AgregarVerbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definicion)
                    .addComponent(txtdefinicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addComponent(agregarverbos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(regresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_AgregarVerbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_AgregarVerbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarverbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarverbosActionPerformed
        try {

            String nombre_verbo = txtnombre_verbo.getText();
            String definicion = txtdefinicion.getText();

            String sql = "insert into verbos (nombre_verbo, definicion)"
                    + "values"
                    + "(?,?)";

            Connection conn = Conexion.getConnection(sql);
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, nombre_verbo);
            statement.setString(2, definicion);

            int filasInsertadas = statement.executeUpdate();

            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(null, "Datos insertados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo insertar los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarverbosActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        close();
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatArcOrangeIJTheme.setup(); //Creacion del look and feel//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVerbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVerbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVerbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVerbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVerbos().setVisible(true);
            }
        });

        //Llamada del metodo para la conexion de la bd
        try {
            Connection conn = Conexion.getConnection("englishOdyssey");

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarverbos;
    private javax.swing.JPanel background_AgregarVerbos;
    private javax.swing.JLabel definicion;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtdefinicion;
    private javax.swing.JTextField txtnombre_verbo;
    private javax.swing.JLabel verbo;
    // End of variables declaration//GEN-END:variables
}
