/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.juegotrivia;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;
import com.mycompany.conexionSQLServer.Conexion;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.*;
import java.awt.event.*;


/**
 *
 * @author javie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */

    
    public Principal() {
        initComponents();
        initStyles();
    }

    //Aqui van los elementos que queramos con estilos
    private void initStyles() {
        titulo.setFont( UIManager.getFont( "h1.font" ) );
        eslogan.setFont( UIManager.getFont( "h2.font" ) );
    }

    //borrar ventana
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_Principal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        eslogan = new javax.swing.JLabel();
        verbo1 = new javax.swing.JButton();
        verbo2 = new javax.swing.JButton();
        verbo3 = new javax.swing.JButton();
        recargar = new javax.swing.JButton();
        agregar_Cartas = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background_Principal.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setBackground(new java.awt.Color(255, 153, 102));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("English Odyssey");

        eslogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eslogan.setText("Journey to Fluency");

        verbo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sin título-2.png"))); // NOI18N
        verbo1.setText("Jump ");
        verbo1.setBorder(null);
        verbo1.setBorderPainted(false);
        verbo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verbo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verbo1.setPreferredSize(new java.awt.Dimension(220, 448));
        verbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verbo1ActionPerformed(evt);
            }
        });

        verbo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sin título-2.png"))); // NOI18N
        verbo2.setText("Meet");
        verbo2.setBorder(null);
        verbo2.setBorderPainted(false);
        verbo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verbo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verbo2.setPreferredSize(new java.awt.Dimension(220, 440));
        verbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verbo2ActionPerformed(evt);
            }
        });

        verbo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sin título-2.png"))); // NOI18N
        verbo3.setText("Paint");
        verbo3.setBorder(null);
        verbo3.setBorderPainted(false);
        verbo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verbo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verbo3.setMaximumSize(new java.awt.Dimension(220, 440));
        verbo3.setMinimumSize(new java.awt.Dimension(220, 440));
        verbo3.setPreferredSize(new java.awt.Dimension(220, 440));
        verbo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verbo3ActionPerformed(evt);
            }
        });

        recargar.setText("Recargar");
        recargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarActionPerformed(evt);
            }
        });

        agregar_Cartas.setText("Agregar verbos");
        agregar_Cartas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar_Cartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_CartasActionPerformed(evt);
            }
        });

        ayuda.setText("Ayuda");
        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background_PrincipalLayout = new javax.swing.GroupLayout(background_Principal);
        background_Principal.setLayout(background_PrincipalLayout);
        background_PrincipalLayout.setHorizontalGroup(
            background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eslogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background_PrincipalLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_Cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verbo2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verbo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        background_PrincipalLayout.setVerticalGroup(
            background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_PrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eslogan)
                .addGap(30, 30, 30)
                .addGroup(background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verbo2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(verbo3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(background_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_Cartas)
                    .addComponent(ayuda)
                    .addComponent(recargar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verbo1ActionPerformed
        close();
        Preguntas preguntas = new Preguntas();
        preguntas.agregarDato(verbo1.getText()); //mandamos dato a otra clase con .agregarDato
        preguntas.setVisible(true);
    }//GEN-LAST:event_verbo1ActionPerformed

    private void recargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarActionPerformed

        try {

            String sql = "select nombre_verbo from verbos order by newid()";

            Connection conn = Conexion.getConnection(sql);

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String verbo1text = rs.getString("nombre_verbo");
                verbo1.setText(verbo1text);
            }
            if (rs.next()) { 
                String verbo2text = rs.getString("nombre_verbo");
                verbo2.setText(verbo2text); 
            }
            if (rs.next()) {
                String verbo3text = rs.getString("nombre_verbo");
                verbo3.setText(verbo3text);
            }

            conn.close();

        } catch (SQLException ex) {

            ex.printStackTrace();

        }

    }//GEN-LAST:event_recargarActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        close();
        Ayuda ayuda = new Ayuda();
        ayuda.setVisible(true);
    }//GEN-LAST:event_ayudaActionPerformed

    private void agregar_CartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_CartasActionPerformed
        close();
        AgregarVerbos agregarVerbos = new AgregarVerbos();
        agregarVerbos.setVisible(true);
    }//GEN-LAST:event_agregar_CartasActionPerformed

    private void verbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verbo2ActionPerformed
        close();
        Preguntas preguntas = new Preguntas();
        preguntas.agregarDato(verbo2.getText());
        preguntas.setVisible(true);
    }//GEN-LAST:event_verbo2ActionPerformed

    private void verbo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verbo3ActionPerformed
        close();
        Preguntas preguntas = new Preguntas();
        preguntas.agregarDato(verbo3.getText());
        preguntas.setVisible(true);
    }//GEN-LAST:event_verbo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatArcOrangeIJTheme.setup(); //Creacion del look and feel

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_Cartas;
    private javax.swing.JButton ayuda;
    private javax.swing.JPanel background_Principal;
    private javax.swing.JLabel eslogan;
    private javax.swing.JButton recargar;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton verbo1;
    private javax.swing.JButton verbo2;
    private javax.swing.JButton verbo3;
    // End of variables declaration//GEN-END:variables
}
